"""populate_tables

Revision ID: 4cd570a5df5a
Revises: 7269e3f382c6
Create Date: 2024-07-31 19:45:51.640919

"""

from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base

from api.tables_models import (
    PlanoSaudeModel,
    ProcedimentoModel,
    EspecialidadeModel,
    PacienteModel,
    MedicoModel,
    ConsultaModel,
    PacientePlanosModel,
    ConsultaProcedimentoModel,
    TelefoneModel,
)

Base = declarative_base()


# revision identifiers, used by Alembic.
revision = "4cd570a5df5a"
down_revision = "e5c072cbb9ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.add_all(
        [
            PlanoSaudeModel(
                plano_descricao="Plano de Saúde Gestão Life",
                plano_telefone="61995863021",
            ),
            ProcedimentoModel(
                proc_nome="Raio X",
                proc_valor=197.90,
            ),
            ProcedimentoModel(
                proc_nome="Consulta",
                proc_valor=100,
            ),
            EspecialidadeModel(
                espec_nome="Cirurgião Dentista",
            ),
            PacienteModel(
                pac_nome="Paulo Abreu",
                pac_data_nascimento="2002-02-10",
            ),
            MedicoModel(
                med_nome="Dr. Vinícius",
                med_crm="123456/SP",
                especialidade_codigo=1,
            ),
            ConsultaModel(
                data=datetime.now(),
                particular=True,
                paciente_codigo=1,
                plano_codigo=1,
                medico_codigo=1,
            ),
        ]
    )
    session.commit()

    session.add_all(
        [
            TelefoneModel(
                telefone="61995863021",
                paciente_codigo=1,
            ),
            PacientePlanosModel(
                paciente_codigo=1,
                plano_codigo=1,
            ),
            ConsultaProcedimentoModel(
                id_consulta=1,
                id_procedimento=1,
            ),
            ConsultaProcedimentoModel(
                id_consulta=1,
                id_procedimento=2,
            ),
        ]
    )
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
