"""inital_tables_scheme

Revision ID: e5c072cbb9ba
Revises: 
Create Date: 2024-07-31 20:54:53.833565

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "e5c072cbb9ba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "especialidade",
        sa.Column("espec_codigo", sa.Integer(), nullable=False),
        sa.Column("espec_nome", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.PrimaryKeyConstraint("espec_codigo"),
    )
    op.create_table(
        "paciente",
        sa.Column("pac_codigo", sa.Integer(), nullable=False),
        sa.Column("pac_data_nascimento", sa.Date(), nullable=False),
        sa.Column("pac_nome", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.PrimaryKeyConstraint("pac_codigo"),
    )
    op.create_table(
        "plano_saucde",
        sa.Column("plan_codigo", sa.Integer(), nullable=False),
        sa.Column("plano_descricao", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("plano_telefone", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.PrimaryKeyConstraint("plan_codigo"),
    )
    op.create_table(
        "procedimento",
        sa.Column("proc_codigo", sa.Integer(), nullable=False),
        sa.Column("proc_nome", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("proc_valor", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("proc_codigo"),
    )
    op.create_table(
        "medico",
        sa.Column("med_codigo", sa.Integer(), nullable=False),
        sa.Column("med_nome", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("med_crm", sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
        sa.Column("especialidade_codigo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["especialidade_codigo"],
            ["especialidade.espec_codigo"],
        ),
        sa.PrimaryKeyConstraint("med_codigo"),
    )
    op.create_table(
        "paciente_plano",
        sa.Column("paciente_codigo", sa.Integer(), nullable=False),
        sa.Column("plano_codigo", sa.Integer(), nullable=False),
        sa.Column("nr_contrato", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["paciente_codigo"],
            ["paciente.pac_codigo"],
        ),
        sa.ForeignKeyConstraint(
            ["plano_codigo"],
            ["plano_saucde.plan_codigo"],
        ),
        sa.PrimaryKeyConstraint("paciente_codigo"),
    )
    op.create_table(
        "paciente_telefone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telefone", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("paciente_codigo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paciente_codigo"],
            ["paciente.pac_codigo"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consulta",
        sa.Column("cons_codigo", sa.Integer(), nullable=False),
        sa.Column("data", sa.DateTime(), nullable=False),
        sa.Column("particular", sa.Boolean(), nullable=False),
        sa.Column("paciente_codigo", sa.Integer(), nullable=False),
        sa.Column("plano_codigo", sa.Integer(), nullable=True),
        sa.Column("medico_codigo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medico_codigo"],
            ["medico.med_codigo"],
        ),
        sa.ForeignKeyConstraint(
            ["paciente_codigo"],
            ["paciente.pac_codigo"],
        ),
        sa.ForeignKeyConstraint(["plano_codigo"], ["plano_saucde.plan_codigo"]),
        sa.PrimaryKeyConstraint("cons_codigo"),
    )
    op.create_table(
        "consulta_procedimento",
        sa.Column("id_consulta", sa.Integer(), nullable=False),
        sa.Column("id_procedimento", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_consulta"],
            ["consulta.cons_codigo"],
        ),
        sa.ForeignKeyConstraint(
            ["id_procedimento"],
            ["procedimento.proc_codigo"],
        ),
        sa.PrimaryKeyConstraint("id_consulta", "id_procedimento"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consulta_procedimento")
    op.drop_table("consulta")
    op.drop_table("paciente_telefone")
    op.drop_table("paciente_plano")
    op.drop_table("medico")
    op.drop_table("procedimento")
    op.drop_table("plano_saucde")
    op.drop_table("paciente")
    op.drop_table("especialidade")
    # ### end Alembic commands ###
